"""add time

Revision ID: 238f104c79fb
Revises: f32f345a32ac
Create Date: 2021-09-11 12:30:08.652340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238f104c79fb'
down_revision = 'f32f345a32ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'time')
    # ### end Alembic commands ###
