"""add download

Revision ID: 81f166064316
Revises: c3d53a0b92b3
Create Date: 2021-07-12 09:09:22.789906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f166064316'
down_revision = 'c3d53a0b92b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('download', sa.Unicode(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'download')
    # ### end Alembic commands ###
