"""remove author

Revision ID: ac59379fafb8
Revises: f3cf63dd5eb0
Create Date: 2022-07-16 09:21:27.776976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac59379fafb8'
down_revision = 'f3cf63dd5eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'author')
    op.drop_column('collection', 'publish_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('publish_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('collection', sa.Column('author', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
