"""remove table

Revision ID: f32f345a32ac
Revises: fd5d34bd0906
Create Date: 2021-07-14 10:58:44.491305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f32f345a32ac'
down_revision = 'fd5d34bd0906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_action')
    op.drop_table('user_action')
    op.drop_table('media_action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_action',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name='media_action_media_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='media_action_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'media_id', name='media_action_pkey')
    )
    op.create_table('user_action',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('affected', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['affected'], ['user.id'], name='user_action_affected_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_action_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'affected', name='user_action_pkey')
    )
    op.create_table('collection_action',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name='collection_action_collection_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='collection_action_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'collection_id', name='collection_action_pkey')
    )
    # ### end Alembic commands ###
