"""add cover data

Revision ID: fd5d34bd0906
Revises: afdf69047bf8
Create Date: 2021-07-14 09:13:00.737345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5d34bd0906'
down_revision = 'afdf69047bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('cover_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'cover_data')
    # ### end Alembic commands ###
