"""create fiction and chapter

Revision ID: 8aa153f3a031
Revises: 707e8ea784e9
Create Date: 2023-03-22 19:36:07.222469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8aa153f3a031'
down_revision = '707e8ea784e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiction',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Unicode(length=300), nullable=True),
    sa.Column('tag', sa.JSON(), nullable=True),
    sa.Column('status', sa.Unicode(length=125), nullable=True),
    sa.Column('short_desc', sa.String(length=160), nullable=True),
    sa.Column('desc', sa.JSON(), nullable=True),
    sa.Column('cover_data', sa.Unicode(length=300), nullable=True),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('download', sa.Unicode(length=500), nullable=True),
    sa.Column('view', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('short_desc', sa.String(length=160), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('fiction_id', postgresql.UUID(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fiction_id'], ['fiction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.drop_table('chapter')
    op.drop_table('fiction')
    # ### end Alembic commands ###
