"""add user type

Revision ID: afdf69047bf8
Revises: 81f166064316
Create Date: 2021-07-13 18:56:02.773951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdf69047bf8'
down_revision = '81f166064316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type')
    # ### end Alembic commands ###
