"""add type table

Revision ID: f3cf63dd5eb0
Revises: d3cec6d6c381
Create Date: 2021-10-24 03:09:40.588685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cf63dd5eb0'
down_revision = 'd3cec6d6c381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('short_desc', sa.String(length=160), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('collection', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collection', 'type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_column('collection', 'type_id')
    op.drop_table('type')
    # ### end Alembic commands ###
